# Generated by Django 3.2.18 on 2023-05-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kami_go', models.CharField(max_length=64, verbose_name='上の句')),
                ('naka_shichi', models.CharField(max_length=64, verbose_name='中の句')),
                ('shimo_go', models.CharField(max_length=64, verbose_name='下の句')),
                ('kami_random', models.TextField(max_length=64, null=True, verbose_name='上ランダム文字')),
                ('naka_random', models.TextField(max_length=64, null=True, verbose_name='中ランダム文字')),
                ('shimo_random', models.TextField(max_length=64, null=True, verbose_name='下ランダム文字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
