# Generated by Django 4.1.3 on 2023-02-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0003_quiz2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz2',
        ),
    ]
