# Generated by Django 4.1.3 on 2023-02-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0004_delete_quiz2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bbs',
            new_name='Post',
        ),
    ]
