# Generated by Django 4.1.3 on 2023-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0005_rename_bbs_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='タグ名')),
            ],
        ),
    ]
