# Generated by Django 4.1.3 on 2023-03-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0007_category_tag_alter_quiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='category1', on_delete=django.db.models.deletion.CASCADE, to='mybbs.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default='tag1', to='mybbs.tag'),
        ),
    ]
