# Generated by Django 4.1.3 on 2023-03-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0010_remove_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
