# Generated by Django 4.1.3 on 2023-03-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0011_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
