# Generated by Django 4.1.3 on 2023-03-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0012_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '01_投稿内容'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
