# Generated by Django 4.1.3 on 2023-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0013_alter_post_options_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
