version: '3'

services:
  web:
    build: .
    tty: true
    volumes:
      #アプリフォルダのこと。（アプリフォルダ配下にxxがある。）
      - ../:/workspace
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: 'linux/amd64'
    volumes:
      #バインドマウント [ホスト側のボリュームmysql_data（＝実フォルダ）をコンテナ内の/var/lib/mysqlとしてマウントしている。]
      - mysql_data:/var/lib/mysql
      #バインドマウント?[コンテナ内の./mysql/dataディレクトリを、コンテナ内の /var/lib/mysql　としてマウントする]
      # - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password

volumes:
    #名前付きボリューム・名ありボリューム（複数のコンテナでボリュームを共有できる。コンテナを削除しても消えない。コンテナに依存しない。）
    mysql_data: