FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN pip install django
RUN pip3 install django_bootstrap5
# RUN pip install --upgrade pip
RUN pip3 install django-environ
RUN pip install mysqlclient
RUN pip install django-mathfilters
RUN pip3 install django-debug-toolbar==3.1
# CMD python3 manage.py runserver 0.0.0.0:8000
