# Generated by Django 3.2.18 on 2023-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhaiku', '0002_auto_20230516_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='naka_random',
            field=models.TextField(max_length=64, null=True, verbose_name='中ランダム文字'),
        ),
    ]
