# Generated by Django 4.1.3 on 2023-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.BigIntegerField(default=0, verbose_name='コメント数'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default=0, verbose_name='Like数'),
        ),
        migrations.AddField(
            model_name='post',
            name='public_range',
            field=models.SmallIntegerField(choices=[(1, '全体'), (2, '会員限定'), (3, '完全限定（利用しない）')], default=1, verbose_name='公開範囲'),
        ),
    ]
