# Generated by Django 4.1.3 on 2023-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
