# Generated by Django 4.1.3 on 2023-03-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='mybbs.tag'),
        ),
    ]
