# Generated by Django 3.2.18 on 2023-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post', to='mybbs.Tag'),
        ),
    ]
